[package]
name = "resource_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
sysinfo = "0.30.7"
yansi = "1.0.1"
clearscreen = "2.0.1"
